apiVersion: v1
kind: Service
metadata:
  name: haproxy
  labels:
    app: haproxy
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31180
  selector:
    app: haproxy
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: haproxy
  labels:
    app: haproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: haproxy
  template:
    metadata:
      labels:
        app: haproxy
    spec:
      containers:
      - name: haproxy
        image: haproxy:2.3
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 0.01
            memory: 32Mi
          limits:
            cpu: 2
            memory: 2Gi
        env:
        - name: ACTIVE_PROFILE
          valueFrom:
            configMapKeyRef:
              name: const-config
              key: active-profile
        - name: EXTRA_CONFIG
          value: '{}'
        - name: WORKER_IP
          valueFrom:
            configMapKeyRef:
              name: const-config
              key: worker-ip
        - name: TZ
          value: Asia/Shanghai
        volumeMounts:
        - name: haproxy
          mountPath: /usr/local/etc/haproxy
          subPath: haproxy    
      volumes:
      - name: haproxy
        persistentVolumeClaim:
          claimName: mt-pvc

